In [1]:
import ast
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

### Section A : Dataset

In [2]:
df = pd.read_csv('dataset.csv')

In [22]:
df.head()

,Transaction_ID,Date,Customer_Name,Items,Total_Items,qty,Total_Cost,Payment_Method,City,Store_Type,Discount_Applied
0,1000000001,2025-01-02 10:15:30,Alice Smith,"['Laptop', 'Wireless Mouse', 'Mousepad', 'Lapt...",4,3,380.50,Credit Card,New York,Tech Retail Store,True
1,1000000002,2025-01-03 14:22:10,Bob Jones,"['Monitor', 'HDMI Cable', 'Mechanical Keyboard']",3,2,245.00,Debit Card,Los Angeles,Online Electronics,False
2,1000000003,2025-01-04 09:40:55,Charlie Brown,"['Smartphone', 'Phone Case', 'Screen Protector...",4,4,650.25,Mobile Payment,Chicago,Warehouse Club,True
3,1000000004,2025-01-05 16:11:00,Diana Prince,"['Bluetooth Speaker', 'Aux Cable', 'Power Bank']",3,2,150.00,Cash,Houston,Tech Retail Store,False
4,1000000005,2025-01-06 11:30:20,Ethan Hunt,"['Tablet', 'Stylus Pen', 'Tablet Cover']",3,3,410.75,Credit Card,Phoenix,Online Electronics,True

In [34]:
df.tail()

,Transaction_ID,Date,Customer_Name,Items,Total_Items,qty,Total_Cost,Payment_Method,City,Store_Type,Discount_Applied
195,1000000196,2025-07-16 12:40:11,Paula Gallagher,"['Gaming Console', 'Headset']",2,1,592.0,Cash,New York,Warehouse Club,False
196,1000000197,2025-07-17 14:15:22,Quentin Clark,"['Smartwatch', 'Wireless Charger']",2,2,238.0,Credit Card,Los Angeles,Tech Retail Store,True
197,1000000198,2025-07-18 11:00:50,Rachel Abbott,"['Wireless Router', 'Ethernet Cable']",2,1,128.0,Debit Card,Chicago,Online Electronics,False
198,1000000199,2025-07-19 15:30:10,Sam Malcolm,"['DSLR Camera', 'Camera Bag']",3,2,772.0,Mobile Payment,Houston,Warehouse Club,True
199,1000000200,2025-07-20 09:20:33,Tina Roberts,"['Portable SSD', 'Flash Drive']",2,1,152.0,Cash,Phoenix,Tech Retail Store,False

### Section B : Data Preprocessing

In [12]:
print("EDA : ")
print(f"Totoal transactions : {len(df)}")
print(f"columns : {list(df.columns)}")
print(f"summary statistics: \n", df[["qty", "Total_Cost", "Total_Items"]].describe())

EDA :
Totoal transactions : 200
columns : ['Transaction_ID', 'Date', 'Customer_Name', 'Items', 'Total_Items', 'qty', 'Total_Cost', 'Payment_Method', 'City', 'Store_Type', 'Discount_Applied']
summary statistics:
               qty  Total_Cost  Total_Items
count  200.000000  200.000000   200.000000
mean     1.820000  353.702500     2.570000
std      0.755283  226.253268     0.698239
min      1.000000   85.000000     2.000000
25%      1.000000  188.750000     2.000000
50%      2.000000  274.000000     2.000000
75%      2.000000  463.500000     3.000000
max      4.000000  970.000000     4.000000

In [14]:
df.isnull().sum()

Transaction_ID      0
Date                0
Customer_Name       0
Items               0
Total_Items         0
qty                 0
Total_Cost          0
Payment_Method      0
City                0
Store_Type          0
Discount_Applied    0
dtype: int64

In [15]:
df["Items"]

0      ['Laptop', 'Wireless Mouse', 'Mousepad', 'Lapt...
1       ['Monitor', 'HDMI Cable', 'Mechanical Keyboard']
2      ['Smartphone', 'Phone Case', 'Screen Protector...
3       ['Bluetooth Speaker', 'Aux Cable', 'Power Bank']
4               ['Tablet', 'Stylus Pen', 'Tablet Cover']
                             ...
195                        ['Gaming Console', 'Headset']
196                   ['Smartwatch', 'Wireless Charger']
197                ['Wireless Router', 'Ethernet Cable']
198                        ['DSLR Camera', 'Camera Bag']
199                      ['Portable SSD', 'Flash Drive']
Name: Items, Length: 200, dtype: str

In [16]:
print(type(df["Items"].iloc[0]))

<class 'str'>

#### Data preprocessing : Convert string representation of list into actual python list

In [18]:
transactions = df["Items"].apply(ast.literal_eval).tolist()

#### Find unique items count across all transactions

In [28]:
flattened_item = [item for sublist in transactions for item in sublist]

unique_items_count = len(set(flattened_item))

In [29]:
print(f"\nNumber of Unique Items: {unique_items_count}")

Number of Unique Items: 33

#### One-hot encoding using TransactionEncoder for Apriori

In [31]:
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)

df_encoded = pd.DataFrame(te_ary, columns = te.columns_)

print( f"\nEncoded Transaction Shape (Rows, Unique Items): {df_encoded.shape}")

Encoded Transaction Shape (Rows, Unique Items): (200, 33)

### Frequent Itemset Mining (Section C Implementation)

In [ ]:
# here minimum support threshold
min_supp_thresh = 0.05

frequent_itemset = apriori(df_encoded, min_support = min_supp_thresh, use_columns = True )